export const BACKLINKS_CLASS = 'backlinks'
export const BACKLINKS_TITLE_CLASS = 'backlinks-title'
export const BACKLINK_TITLE_CLASS = 'backlink-title'
export const BACKLINK_PATH_CLASS = 'backlink-path'
export const MENTIONS_CLASS = 'mentions'
export const MENTION_ROW_CLASS = 'mention-row'
export const MENTION_ACTION_CLASS = 'mention-action'
