export const BLOCK_ANCHOR_PREFIX = '^'
export const BLOCK_ID_TRAILING_PATTERN = /(^|[ \t])\^([A-Za-z0-9-]+)[ \t]*$/
export const BLOCK_ID_STANDALONE_PATTERN = /^\^([A-Za-z0-9-]+)$/
export const BLOCK_ID_LIVE_CLASS = 'cm-live-block-id'
export const BLOCK_ID_MUTED_OPACITY = 0.45
export const BLOCK_ID_ATTRIBUTE = 'data-block-id'
export const BLOCK_HIGHLIGHT_CLASS = 'block-target'
export const LIST_ITEM_PATTERN = /^(\s*)(?:[-*+]|\d+[.)])\s+/
export const BLOCK_HIGHLIGHT_DURATION = 2000
export const ANCHOR_PARAM = 'anchor'
export const BLOCK_PREVIEW_MAX_LENGTH = 60
export const BLOCK_COMPLETION_PATTERN = /\[\[([^\]|#]*)#\^([^\]|]*)$/
export const BLOCK_ID_LENGTH = 6
export const BLOCK_ID_ALPHABET = 'abcdefghijklmnopqrstuvwxyz0123456789'
export const BLOCK_NON_TARGET_PATTERN = /^(#{1,6}\s|\||[-*_]{3,}\s*$)/
