export const TREE_BRANCHING = 3
export const NOTES_PER_FOLDER = 3
export const LEGACY_SEED_IMAGE_FILENAME = 'legacy-seed-image.png'
export const LEGACY_SEED_IMAGE_BASE64 = 'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z8BQDwAEhQGAhKmMIQAAAABJRU5ErkJggg=='
