export const HEADING_PATTERN = /^(#{1,6})[ \t]+(.+?)(?:[ \t]+#+)?\s*$/
export const HEADING_SELECTOR = 'h1, h2, h3, h4, h5, h6'
export const HEADING_OUTLINE_INDENT = 24
export const HEADING_OUTLINE_CHEVRON_SIZE = 18
export const HEADING_OUTLINE_GUIDE_WIDTH = 1
export const HEADING_SCALE = [2, 1.8, 1.6, 1.5, 1.4, 1.2]
export const HEADING_PREFIX_PATTERN = /^(#{1,6})\s/
export const HEADING_LINE_PATTERN = /^(#{1,6})\s+(.*)$/
export const HEADING_MARKER_PATTERN = /^#{1,6}\s+/
