export const MARKDOWN_ACTIONS = {
    BOLD: 'bold',
    ITALIC: 'italic',
    STRIKE: 'strike',
    CODE: 'code',
    H0: 'h0',
    H1: 'h1',
    H2: 'h2',
    H3: 'h3',
    H4: 'h4',
    H5: 'h5',
    H6: 'h6',
    QUOTE: 'quote',
    HR: 'hr',
    IMAGE: 'image',
    IMAGE_EMBED: 'image-embed',
    LINK: 'link',
    WIKI_LINK: 'wiki-link',
    LIST_BULLET: 'list-bullet',
    LIST_ORDERED: 'list-ordered',
    LIST_CHECKLIST: 'list-checklist',
    INDENT: 'indent',
    OUTDENT: 'outdent',
    FOLD: 'fold',
    INSERT_DATE: 'insert-date',
    INSERT_TIME: 'insert-time',
    INSERT_TITLE: 'insert-title',
    UNDO: 'undo',
    REDO: 'redo',
    SEARCH_NEXT: 'search-next',
    SEARCH_PREVIOUS: 'search-previous',
    SEARCH_REPLACE: 'search-replace',
    SEARCH_REPLACE_ALL: 'search-replace-all',
    TABLE: 'table'
}

export const HEADING_ACTION_LEVELS = {
    [MARKDOWN_ACTIONS.H1]: 1,
    [MARKDOWN_ACTIONS.H2]: 2,
    [MARKDOWN_ACTIONS.H3]: 3,
    [MARKDOWN_ACTIONS.H4]: 4,
    [MARKDOWN_ACTIONS.H5]: 5,
    [MARKDOWN_ACTIONS.H6]: 6
}
