export const MIME_TYPES = {
    MARKDOWN: 'text/markdown',
    HTML: 'text/html',
    JSON: 'application/json',
    PDF: 'application/pdf',
    TEXT: 'text/plain',
    GIF: 'image/gif',
    WEBP: 'image/webp',
    SVG: 'image/svg+xml',
    BMP: 'image/bmp',
    AVIF: 'image/avif',
    MP3: 'audio/mpeg',
    WAV: 'audio/wav',
    M4A: 'audio/mp4',
    OGG_AUDIO: 'audio/ogg',
    FLAC: 'audio/flac',
    GPP3: 'audio/3gpp',
    MP4: 'video/mp4',
    WEBM: 'video/webm',
    OGG_VIDEO: 'video/ogg',
    QUICKTIME: 'video/quicktime',
    MATROSKA: 'video/x-matroska',
    JPEG: 'image/jpeg',
    PNG: 'image/png',
    FONT_TTF: 'font/ttf',
    FONT_WOFF2: 'font/woff2'
}
