export const SYNTAX_IMAGE_FILENAME = 'syntax-sample.png'
export const SYNTAX_IMAGE_BASE64 = 'iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAIAAAAlC+aJAAAAc0lEQVR42u3QoRGAUBBDwSsMg6IQFJLaKAZNJZ8acurEzrwCsql1HlHbc0ft1xe13ooqAAAAAAAAAAAAAIA2YNqg9FAAAAAAAAAAAAAAgD5g2qD0UAAAAAAAAAAAAACAPmDaoPRQAAAAAAAAAAAAAIA24Af+5Kl41G3YzwAAAABJRU5ErkJggg=='

export const SYNTAX_LINKED_TITLE = 'Nota enlazada'
export const SYNTAX_EMBED_TITLE = 'Nota para embeber'
export const SYNTAX_MAIN_TITLE = 'Guía de sintaxis de Notes'

export const SYNTAX_LINKED_TAGS = ['pruebas/enlaces']
export const SYNTAX_EMBED_TAGS = ['pruebas/embeds']
export const SYNTAX_MAIN_TAGS = ['pruebas', 'pruebas/sintaxis', 'app/notes']

export const SYNTAX_LINKED_PROPERTIES = { aliases: ['Alias de prueba'] }
export const SYNTAX_MAIN_PROPERTIES = { aliases: ['Sintaxis completa'], autor: 'Equipo de Notes', version: 1, fecha: '2026-01-15', recordatorio: '2026-01-15T09:30' }

export const SYNTAX_LINKED_BODY = [
    '# Nota enlazada',
    '',
    'Esta nota es el destino de los enlaces de la [[Guía de sintaxis de Notes]].',
    '',
    '## Sección uno',
    '',
    'Contenido de la primera sección. Sirve para probar `[[Nota enlazada#Sección uno]]`. Al renombrar este encabezado se actualizan los enlaces de la guía.',
    '',
    '## Sección dos',
    '',
    'Contenido de la segunda sección con ==texto resaltado==.',
    '',
    '## Bloques',
    '',
    'Este párrafo se puede enlazar y embeber por su id. ^bloque-prueba',
    '',
    '- Elemento de lista sin id',
    '- Elemento de lista con id ^lista-prueba',
    ''
].join('\n')

export const SYNTAX_EMBED_BODY = [
    'Este texto viene de **otra nota** y se muestra dentro de la guía.',
    '',
    '- Primer punto con ==resaltado==',
    '- Segundo punto con un enlace a [[Nota enlazada]]',
    '',
    '%%Este comentario no debe verse%%',
    ''
].join('\n')

export const SYNTAX_MAIN_BODY = [
    'Notes es una app de notas en markdown que guarda cada nota como un archivo `.md` dentro de tus carpetas.',
    'Esta guía reúne **toda la sintaxis implementada** para probarla en los tres modos: Lectura, Edición y Código.',
    '',
    '## 1. Encabezados',
    '',
    '# Encabezado 1',
    '## Encabezado 2',
    '### Encabezado 3',
    '#### Encabezado 4',
    '##### Encabezado 5',
    '###### Encabezado 6',
    '',
    '## 2. Estilos de texto',
    '',
    'Texto en **negrita**, en *cursiva*, en ***negrita y cursiva***, ~~tachado~~ y `código en línea`.',
    '',
    'También __negrita con guiones bajos__ y _cursiva con guiones bajos_.',
    '',
    'Texto con ==resaltado== y con ==resaltado con **negrita** dentro==.',
    '',
    'Un comentario oculto %%esto no se muestra en lectura%% está en medio de esta frase.',
    '',
    '%%',
    'Comentario de varias líneas',
    'que tampoco se muestra.',
    '%%',
    '',
    'Dentro de código no se interpreta: `==no resaltar==` y `%%no comentar%%`.',
    '',
    'Escapes: \\*no cursiva\\*, \\==no resaltado\\==, \\#no-es-tag.',
    '',
    '## 3. Listas',
    '',
    '- Elemento con guion',
    '- Otro elemento',
    '    - Anidado nivel dos',
    '        - Anidado nivel tres',
    '',
    '* Elemento con asterisco',
    '+ Elemento con más',
    '',
    '1. Primer paso',
    '2. Segundo paso',
    '    1. Subpaso',
    '    2. Otro subpaso',
    '3. Tercer paso',
    '',
    '### Tareas',
    '',
    '- [ ] Tarea pendiente',
    '- [x] Tarea completada',
    '- [ ] Tarea con **formato** y ==resaltado==',
    '    - [ ] Subtarea',
    '- [/] Estado personalizado: en curso',
    '- [-] Estado personalizado: cancelada',
    '- [>] Estado personalizado: aplazada',
    '',
    '## 4. Citas y callouts',
    '',
    '> Una cita simple.',
    '> Continúa en la segunda línea.',
    '',
    '> Cita con **formato**',
    '>',
    '> > Cita anidada',
    '',
    '> [!note] Nota',
    '> Callout de tipo note con título propio.',
    '',
    '> [!abstract] Resumen',
    '> Callout abstract.',
    '',
    '> [!info]',
    '> Callout info sin título: usa el nombre del tipo.',
    '',
    '> [!todo] Pendiente',
    '> Callout todo.',
    '',
    '> [!tip] Consejo',
    '> Callout tip con `código` y [[Nota enlazada]].',
    '',
    '> [!success] Éxito',
    '> Callout success.',
    '',
    '> [!question] Pregunta',
    '> Callout question.',
    '',
    '> [!warning] Advertencia',
    '> Callout warning.',
    '',
    '> [!failure] Fallo',
    '> Callout failure.',
    '',
    '> [!danger] Peligro',
    '> Callout danger.',
    '',
    '> [!bug] Error',
    '> Callout bug.',
    '',
    '> [!example] Ejemplo',
    '> Callout example.',
    '',
    '> [!quote] Cita',
    '> Callout quote.',
    '',
    '> [!summary] Alias de abstract',
    '> Los alias como summary, hint, check o error usan el estilo de su tipo base.',
    '',
    '> [!hint]- Plegado por defecto',
    '> Este contenido está oculto hasta que se despliega.',
    '',
    '> [!faq]+ Desplegado por defecto',
    '> Este contenido se muestra y se puede plegar.',
    '',
    '> [!desconocido] Tipo desconocido',
    '> Un tipo que no existe usa el estilo de note.',
    '',
    '## 5. Enlaces',
    '',
    '- Enlace web: [Expo](https://expo.dev)',
    '- Enlace automático: https://reactnative.dev',
    '- Correo: [Escribir](mailto:hola@example.com)',
    '- Teléfono: [Llamar](tel:+5255555555)',
    '',
    '### Enlaces internos',
    '',
    '- Enlace a una nota: [[Nota enlazada]]',
    '- Con texto alternativo: [[Nota enlazada|esta otra nota]]',
    '- A una sección: [[Nota enlazada#Sección uno]]',
    '- A una sección sin importar mayúsculas: [[Nota enlazada#sección uno|con alias]]',
    '- A una sección que no existe: [[Nota enlazada#Sección inexistente]]',
    '- A un encabezado de esta misma nota: [[#6. Embeds]]',
    '- A un bloque: [[Nota enlazada#^bloque-prueba]]',
    '- A un bloque de lista: [[Nota enlazada#^lista-prueba]]',
    '- A un bloque que no existe: [[Nota enlazada#^no-existe]]',
    '- Por alias de la nota: [[Alias de prueba]]',
    '- Con nombre en minúsculas: [[nota enlazada]]',
    '- Enlace roto: [[Esta nota no existe]]',
    '',
    '## 6. Embeds',
    '',
    'Nota embebida:',
    '',
    '![[Nota para embeber]]',
    '',
    'Sección embebida (desde su encabezado hasta el siguiente):',
    '',
    '![[Nota enlazada#Sección uno]]',
    '',
    'Bloque embebido (solo ese párrafo):',
    '',
    '![[Nota enlazada#^bloque-prueba]]',
    '',
    'Bloque embebido que no existe:',
    '',
    '![[Nota enlazada#^no-existe]]',
    '',
    'Imagen embebida:',
    '',
    '![[syntax-sample.png]]',
    '',
    'Imagen con ancho de 120 px:',
    '',
    '![[syntax-sample.png|120]]',
    '',
    'Embed roto:',
    '',
    '![[Embed que no existe]]',
    '',
    'Bloque con id propio en esta nota, enlazable desde otras. ^bloque-guia',
    '',
    '## 7. Etiquetas',
    '',
    'Etiquetas en línea: #app #app/editor #app/editor/modos #pruebas/sintaxis y #etiqueta-con-guiones.',
    '',
    'No son etiquetas: `#en-codigo`, un hash suelto # o texto como a#b.',
    '',
    'Las etiquetas del frontmatter (`pruebas`, `pruebas/sintaxis`, `app/notes`) se editan en el panel de propiedades.',
    '',
    '## 8. Tablas',
    '',
    '| Función | Modo | Estado |',
    '| :--- | :---: | ---: |',
    '| Resaltado | Lectura y edición | Listo |',
    '| Callouts | Lectura y edición | Listo |',
    '| Embeds | Solo lectura | Listo |',
    '| Búsqueda con operadores | Búsqueda | Listo |',
    '',
    '## 9. Código',
    '',
    'Bloque con lenguaje:',
    '',
    '```js',
    'const saludo = (nombre) => `Hola, ${nombre}`',
    'console.log(saludo("Notes"))',
    '```',
    '',
    'Bloque sin lenguaje:',
    '',
    '```',
    'texto plano ==sin resaltar== %%sin ocultar%% #sin-tag',
    '```',
    '',
    'Bloque con tildes:',
    '',
    '~~~json',
    '{ "app": "notes", "modos": ["lectura", "edicion", "codigo"] }',
    '~~~',
    '',
    '    Bloque con sangría de cuatro espacios',
    '',
    '## 10. Matemáticas',
    '',
    'En línea: $E = mc^2$ y $\\alpha + \\beta = \\gamma$.',
    '',
    'En bloque:',
    '',
    '$$',
    '\\int_0^1 x^2 \\, dx = \\frac{1}{3}',
    '$$',
    '',
    '$$',
    '\\sum_{i=1}^{n} i = \\frac{n(n+1)}{2}',
    '$$',
    '',
    '## 11. Notas al pie',
    '',
    'Esta frase tiene una nota al pie[^1] y otra más[^larga].',
    '',
    '[^1]: Contenido de la primera nota al pie.',
    '[^larga]: Una nota al pie con **formato** y un enlace a [[Nota enlazada]].',
    '',
    'Nota al pie en línea^[Se escribe dentro del propio texto, sin definición aparte.].',
    '',
    '## 12. Separadores',
    '',
    '---',
    '',
    '***',
    '',
    '___',
    '',
    '## 13. HTML',
    '',
    '<div style="padding:12px;border:1px solid currentColor;border-radius:8px">Caja con HTML en línea</div>',
    '',
    '<details><summary>Detalles desplegables</summary>',
    '',
    'Contenido dentro de un `details` nativo.',
    '',
    '</details>',
    '',
    'Texto con <mark>mark</mark>, <sup>superíndice</sup> y <sub>subíndice</sub>.',
    '',
    '## 14. Búsqueda',
    '',
    'Operadores para probar en el buscador:',
    '',
    '- `tag:pruebas` o `tag:#pruebas/sintaxis`',
    '- `path:pruebas` y `file:guía`',
    '- `is:pinned`, `has:image` (solo con imágenes insertadas como `![](url)`) e `in:content`',
    '- `modified:2026-01-01` y `created:2026-01-01`',
    '',
    '## 15. Texto largo y caracteres especiales',
    '',
    'Acentos y eñes: canción, pingüino, niño, über. Símbolos: © ® ™ € £ ¥ → ← ↑ ↓ ✓ ✗.',
    '',
    'Emoji: 📝 ✅ 🚀',
    '',
    'Línea larga sin espacios para probar el corte: ' + 'abcdefghij'.repeat(12),
    ''
].join('\n')
